apiVersion: v1
kind: Secret
metadata:
  name: example-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "secret_id": "my_secretid",
      "secret_key": "my_secretkey",
      "region": "ap-hongkong"
    }